export interface ITablList {
  nonce: number;
  result: {
    top: number[];
    bottom: number[];
    number: number;
  };
}
export interface IQueryInfo {
  serverSeed?: string;
  clientSeed?: string;
  nonce?: string;
  app?: string;
}

export const Probabilitys = {
  products: [
    {
      id: 1145,
      name: "Lucky Scratch ₹30",
      description: "Win up to ₹20,000 with this exciting scratch card!",
      coin: 30,
      status: 1,
      type: "power",
      card_grid_num: 25,
      probability_config: {
        codes: [
          "armcar",
          "banana",
          "bank",
          "bell",
          "boat",
          "car",
          "cem",
          "cherry",
          "chest",
          "coin",
          "crown",
          "glasses",
          "gold",
          "heart",
          "hoe",
          "joker",
          "key",
          "lemon",
          "lightn",
          "money",
          "moon",
          "muffin",
          "necklace",
          "orange",
          "pear",
          "pearl",
          "piggybank",
          "pineapl",
          "rinbow",
          "ring",
          "safe",
          "scale",
          "shoe",
          "star",
          "strawberry",
          "sun",
          "tophat",
          "tree",
          "trophy",
          "vault",
        ],
        empty_awards_coins: [
          30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800,
          900, 1000,
        ],
        awards: [
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 70,
            probability: 0.3,
            name: "prize 70",
          },
          {
            code: "code2",
            type: "normal",
            symbol: "rupee",
            coin: 30,
            probability: 0.7,
            name: "prize 30",
          },
        ],
        empty_awards: [
          {
            code: "code1",
            type: "normal",
            symbol: "acco",
            coin: 20000,
            probability: 0.00059591,
            name: "prize 20000",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "acco",
            coin: 2000,
            probability: 0.00595908,
            name: "prize 2000",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "20X",
            coin: 600,
            probability: 0.01986362,
            name: "prize 600",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "5X",
            coin: 150,
            probability: 0.05959085,
            name: "prize 150",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "acco",
            coin: 500,
            probability: 0.59590849,
            name: "prize 500",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 200,
            probability: 1.98636164,
            name: "prize 200",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 100,
            probability: 5.95908492,
            name: "prize 100",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 60,
            probability: 11.91816985,
            name: "prize 60",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 30,
            probability: 19.86361641,
            name: "prize 30",
          },
        ],
      },
    },
    {
      id: 1146,
      name: "wild-3",
      description: "Win up to ₹20,000 with this exciting scratch card!",
      coin: 30,
      status: 1,
      type: "wild",
      card_grid_num: 13,
      top_grid_num: 3,
      Bottom_grid_num: 10,
      probability_config: {
        empty_awards_coins: [
          30, 40, 50, 60, 70, 80, 90, 100, 200, 300, 400, 500, 600, 700, 800,
          900, 1000,
        ],
        awards: [
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 250000,
            probability: 0.0051,
            name: "prize 250000",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 1250,
            probability: 0.0254,
            name: "prize 1250",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 250,
            probability: 0.2542,
            name: "prize 250",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 125,
            probability: 0.5085,
            name: "prize 125",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 100,
            probability: 0.7627,
            name: "prize 100",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 50,
            probability: 0.8778,
            name: "prize 50",
          },
          {
            code: "code1",
            type: "normal",
            symbol: "rupee",
            coin: 25,
            probability: 22.99,
            name: "prize 25",
          },
        ],
      },
    },
  ],
};
